# Generated by Django 5.2 on 2025-04-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='zip_number',
            field=models.CharField(max_length=10),
        ),
    ]
